version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - default

  bot:
    build: .
    container_name: "exchange_bot"
    environment:
      - TOKEN=<7251950237:AAEXAgkQhD45EFLDi5xYLPEQxwVMgTkgGbQ>
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    command: ["python", "main.py"]
    networks:
      - default

networks:
  default:
    driver: bridge